name: Run SCA Analysis

on:
    workflow_call:
        inputs:
            manifest-path:
                description: Path to the manifest to analyze
                required: true
                type: string
            severity:
                description: The severity level to require for a vulnerable library.
                required: false
                type: string
            java-version:
                description: The java version to use
                required: false
                type: string
                default: '11'
            java-distribution:
                description: The java distribution to use
                required: false
                type: string
                default: 'zulu'
            sca-teamserver-url:
                description: The TeamServer instance to report results to
                required: false
                type: string
                default: ${{ vars.TEAMSERVER_SCA_URL }}
            sca-teamserver-org:
                description: The Organization UUID to report results to
                required: false
                type: string
                default: ${{ vars.TEAMSERVER_SCA_ORGANIZATION_ID }}
        secrets:
            TEAMSERVER_SCA_API_KEY:
                required: true
            TEAMSERVER_SCA_AUTH_KEY:
                required: true

jobs:
    run-sca-analysis:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

            - name: Setup java
              uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
              with:
                  distribution: ${{ inputs.java-distribution }}
                  java-version: ${{ inputs.java-version }}

            - name: SCA Analysis
              uses: Contrast-Security-OSS/contrast-sca-action@70b64cbbf06600970ab89c4360976fd0749c2d7c # master
              with:
                  apiKey: ${{ secrets.TEAMSERVER_SCA_API_KEY }}
                  orgId: ${{ inputs.sca-teamserver-org }}
                  authHeader: ${{ secrets.TEAMSERVER_SCA_AUTH_KEY }}
                  apiUrl: ${{ inputs.sca-teamserver-url }}
                  filePath: ${{ inputs.manifest-path }}
                  fail: ${{ inputs.severity != null }}
                  severity: ${{ inputs.severity }}
